apiVersion: apps/v1
kind: Deployment
metadata:
  name: localai-worker
  namespace: localai
  labels:
    app: localai-worker
spec:
  replicas: 3  # Number of workers
  selector:
    matchLabels:
      app: localai-worker
  template:
    metadata:
      labels:
        app: localai-worker
    spec:
      containers:
      - name: localai-worker
        image: localai/localai:v2.20.1-cublas-cuda12-core
        ports:
        - containerPort: 8000  # Worker port for llama-cpp-RPC
        args:
        - worker
        - p2p-llama-cpp-rpc
        env:
        - name: "TOKEN"
          valueFrom:
            secretKeyRef:
              name: localai-worker-token
              key: token
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
