apiVersion: v1
kind: Service
metadata:
  name: localai
  namespace: localai
  labels:
    app: localai
spec:
  selector:
    app: localai
  ports:
    - protocol: TCP
      port: 8080            # External port (reachable from outside)
      targetPort: 8080      # The port where LocalAI listens inside the pod
  type: ClusterIP        # Cloud provider-managed external LoadBalancer
